/// THIS FILE IS GENERATED BY r_resources. DO NOT MODIFY MANUALLY.

// ignore_for_file: avoid_classes_with_only_static_members,always_specify_types,lines_longer_than_80_chars,non_constant_identifier_names,prefer_double_quotes,unnecessary_raw_strings,use_raw_strings


class R {
  static const images = _ImageResources();
  static const svg = _SvgResources();
}

class _ImageResources {
  const _ImageResources();

  /// ![](/Users/codruterdei/Engineering/wheel_of_names/assets/images/flutter_logo.png)
  final flutter_logo = r'assets/images/flutter_logo.png';
}

class _SvgResources {
  const _SvgResources();
}
